yamldefault_watchlist:
  - "AAPL"
  - "MSFT" 
  - "GOOGL"
  - "AMZN"
  - "TSLA"
  - "NVDA"
  - "META"
  - "JPM"
  - "V"
  - "JNJ"
  - "PLTR"
  - "AMD"
  - "COIN"
  - "GME"
  - "RIVN"
  - "SNOW"
  - "CRWD"
  - "NET"
  - "ARKK"
  - "SPY"